# Resource Locations

bwa_reference:
  /state/partition1/db/human/mappers/b37/bwa/human_g1k_v37.fasta
reference:
  /state/partition1/db/human/gatk/2.8/b37/human_g1k_v37.fasta
dbsnp_vcf:
  /data/db/human/gatk/2.8/b37/dbsnp_138.b37_new.vcf.gz
gene_bed_file:
  /data/results/181129_NB551415_0005_AHWW37BGX7/NIPD1/config/NIPDv6/beds/NIPDv6_genes.bed
capture_bed_file:
  /data/results/181129_NB551415_0005_AHWW37BGX7/NIPD1/config/NIPDv6/beds/NIPDv6_capture_targets.bed
primary_bed_file:
  /data/results/181129_NB551415_0005_AHWW37BGX7/NIPD1/config/NIPDv6/beds/NIPDv6_primary_targets.bed
reference_sequence_dict:
  /data/db/human/mappers/b37/bwa/human_g1k_v37.dict
picard_temp_dir:
  /state/partition1/tmpdir
fastqc_temp_dir:
  /state/partition1/tmpdir
samtools_temp_dir:
  /state/partition1/tmpdir
vep_cache:
  /share/data/db/human/vep/vep_cache

# Threads to Use
bwa_threads:
  12
fastp_threads:
  12
fastqc_threads:
  12
mosdepth_threads:
  1
vep_threads:
  6

# Java Options
java_home: #activate conda environment and type which java - needed for cluster
  /home/transfer/miniconda3/envs/nipd/bin/java
gatk_hc_java_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir -Xmx16g
gatk_bqsr_java_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir -Xmx8g
gatk_analyse_covariates_java_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir-Xmx8g
gatk_variants_java_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir -Xmx4g
gatk_genomics_db_java_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir -Xmx16g
picard_memory_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir -Xmx32g

# Misc Settings
# Max records in picard MarkDuplicates
merge_duplicates_max_records:
  2000000
# chromsomes to to scatter gather on
chromosomes:
  ['7', '9', '16', 'X']
interval_padding_haplotype_caller:
  100

# Run Level Information
seqID:
  181129_NB551415_0005_AHWW37BGX7
platform:
  ILLUMINA
worklistId:
  test
flowcell:
  my_flowcell
centre:
  AWGL
pipelineName:
  NIPD
pipelineVersion:
  0.0.1
panel:
  NIPD1

# Variant Filtering
min_QD:
  2.0
max_FS:
  60.0
max_SOR:
  3.0
min_MQ:
  40.0
min_MQRankSum:
  -12.5
min_ReadPosRankSum:
  -8.0

samples:
  [14M01888,14M02709,F1-15,F2-10,F3-8,F4-5,F5-2,16M96501,16M96867,F5-2-DIL]

sample_numbers:
  [S1, S2, S3, S4, S5, S6, S7, S8, S9, S10]

families:
  FAM001:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F1-15
      proband: 14M02709
      father: null
  FAM002:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F2-10
      proband: 14M02709
      father: null
  FAM003:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F3-8
      proband: 14M02709
      father: null
  FAM004:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F4-5
      proband: 14M02709
      father: null
  FAM005:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F5-2
      proband: 14M02709
      father: null
  FAM006:
    analysis_required: X-linked
    members:
      mother: null
      plasma: 16M96501
      proband: null
      father: null
  FAM007:
    analysis_required: X-linked
    members:
      mother: null
      plasma: 16M96867
      proband: null
      father: null
  FAM008:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F5-2-DIL
      proband: 14M02709
      father: null



