# Resource Locations

bwa_reference:
  /data/resources/human/mappers/b37/bwa/human_g1k_v37.fasta
reference:
  /data/resources/human/gatk/2.8/b37/human_g1k_v37.fasta
gene_bed_file:
  config/NIPDFinal/beds/nipd_final_genes.bed
roi_bed_file:
  config/NIPDFinal/beds/nipd_final_roi.bed
padded_roi_bed_file:
  config/NIPDFinal/beds/nipd_final_roi_padded30.bed
exon_bed_file:
  config/NIPDFinal/beds/nipd_final_exons_padded30.bed
snp_bed:
  config/NIPDFinal/beds/nipd_final_snp_coordinates.bed
reference_sequence_dict:
  /data/resources/human/gatk/2.8/b37/human_g1k_v37.dict
vep_cache_location:
  /data/resources/human/vep-cache/refseq37_v100
gnomad_exomes:
  /data/resources/human/gnomad/gnomad.exomes.r2.0.1.sites.vcf.gz
gnomad_genomes:
  /data/resources/human/gnomad/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz
picard_temp_dir:
  /localscratch/
fastqc_temp_dir:
  /localscratch/
samtools_temp_dir:
  /localscratch/


# Threads to Use
bwa_threads:
  10
fastp_threads:
  10
fastq_screen_threads:
  10
fastqc_threads:
  10
vep_threads:
  10
platypus_threads:
  10



# Java Options

picard_memory_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/localscratch/ -Xmx20g

# Misc Settings
# Max records in picard MarkDuplicates
merge_duplicates_max_records:
  2000000

# Run Level Information
seqID:
  191104_NB551319_0035_AHNGHLAFXY
platform:
  ILLUMINA
worklistId:
  test
flowcell:
  my_flowcell
centre:
  AWGL
pipelineName:
  NIPD
pipelineVersion:
  development
panel:
  NIPD

families:
  FAM001:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F1-15
      proband: 14M02709
      father: null
  FAM002:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F2-10
      proband: 14M02709
      father: null
  FAM003:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F3-8
      proband: 14M02709
      father: null
  FAM004:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F4-5
      proband: 14M02709
      father: null
  FAM005:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F5-2
      proband: 14M02709
      father: null
  FAM006:
    analysis_required: X-linked
    members:
      mother: null
      plasma: 16M96501
      proband: null
      father: null
  FAM007:
    analysis_required: X-linked
    members:
      mother: null
      plasma: 16M96867
      proband: null
      father: null
  FAM008:
    analysis_required: X-linked
    members:
      mother: 14M01888
      plasma: F5-2-DIL
      proband: 14M02709
      father: null







