# Resource Locations

bwa_reference:
  /state/partition1/db/human/mappers/b37/bwa/human_g1k_v37.fasta
reference:
  /state/partition1/db/human/gatk/2.8/b37/human_g1k_v37.fasta
ref_sequence_dict:
   /state/partition1/db/human/gatk/2.8/b37/human_g1k_v37.dict
gene_bed_file:
  /share/data/diagnostics/pipelines/NIPD/NIPD-development/config/NIPDFinal/beds/nipd_final_genes.bed
roi_bed_file:
  /share/data/diagnostics/pipelines/NIPD/NIPD-development/config/NIPDFinal/beds/nipd_final_roi.bed
padded_roi_bed_file:
  /share/data/diagnostics/pipelines/NIPD/NIPD-development/config/NIPDFinal/beds/nipd_final_roi_padded30.bed
exon_bed_file:
  /share/data/diagnostics/pipelines/NIPD/NIPD-development/config/NIPDFinal/beds/nipd_final_exons_padded30.bed
snp_bed:
  /share/data/diagnostics/pipelines/NIPD/NIPD-development/config/NIPDFinal/beds/nipd_final_snp_coordinates.bed
reference_sequence_dict:
  /share/data/db/human/mappers/b37/bwa/human_g1k_v37.dict
vep_cache_location:
  /share/data/db/human/vep_cache/refseq37/
gnomad_exomes:
  /share/data/db/human/gnomad/gnomad.exomes.r2.0.1.sites.vcf.gz
gnomad_genomes:
  /share/data/db/human/gnomad/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz
picard_temp_dir:
  /state/partition1/tmpdir/
fastqc_temp_dir:
  /state/partition1/tmpdir/
samtools_temp_dir:
  /state/partition1/tmpdir/


# Threads to Use
bwa_threads:
  12
fastp_threads:
  12
fastq_screen_threads:
  12
fastqc_threads:
  12
vep_threads:
  12


# Java Options
java_home:
  /home/transfer/miniconda3/envs/nipd/bin/java
gatk_bqsr_java_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir -Xmx4g
gatk_analyse_covariates_java_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir -Xmx2g
gatk_variants_java_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir -Xmx4g
picard_memory_options:
  -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/state/partition1/tmpdir -Xmx20g

# Misc Settings
# Max records in picard MarkDuplicates
merge_duplicates_max_records:
  2000000
chromosomes:
  ['7', '9', '16', 'X']


# Run Level Information
seqID:
  181129_NB551415_0005_AHWW37BGX7
platform:
  ILLUMINA
worklistId:
  test
flowcell:
  my_flowcell
centre:
  AWGL
pipelineName:
  NIPD
pipelineVersion:
  0.0.1
panel:
  NIPD1
